# Config file in TOML format (https://github.com/toml-lang/toml)

verbose = true

[job_scheduler]
use_scheduler = true

    [job_scheduler.args]
    scheduler_name = "sge"
    submit_command = "qsub"
    queue_name = "all.q"
    prefix_command = "source ~/.bashrc; source /path/to/venv/bin/activate; ulimit -c 0"

[extract]
from_fasta = true
db_prefix = "READS"
out_fname = "tr_reads.pkl"

    [extract.fasta_to_db]
    fasta_fname = "reads.fasta"
    db_block_size = 500

    [extract.tr_detection]
    n_core = 8

    [extract.unit_detection]
    n_core = 10
    n_distribute = 5
    max_cv = 0.1
    max_slope_dev = 0.05

    [extract.load_qv]
    fastq_fname = "reads.fastq"
    #mean_qv = 20

[filter]
min_n_units = 10
min_ulen = 320
max_ulen = 380
out_fname = "filtered_reads.pkl"

[assemble]
reads_fname = "filtered_reads.pkl"

    [assemble.unsync_overlap]
    global = false
    n_core = 10
    n_distribute = 10
    unsync_ovlps_fname = "unsync_overlaps.pkl"

    [assemble.unit_sync]
    n_core = 10
    n_distribute = 10
    sync_reads_fname = "sync_reads.pkl"

    [assemble.unit_clustering]
    n_core = 10
    n_distribute = 10
    smdc_reads_fname = "smdc_reads.pkl"

    [assemble.sync_overlap]
    n_core = 10
    n_distribute = 10
    smdc_ovlps_fname = "sync_overlaps.pkl"

    [assemble.layout]
    n_core = 10
    contigs_fname = "contigs.fasta"
